import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1778547355958 implements MigrationInterface {
    name = 'Init1778547355958'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "mst_strategy_group" ("id" SERIAL NOT NULL, "code" character varying(50) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_b2078fe94fe967d0108e3382959" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c90519c0ca5335fb813b713d75" ON "mst_strategy_group" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_strategy" ("id" SERIAL NOT NULL, "code" character varying(50) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "is_active" boolean NOT NULL DEFAULT true, "mst_strategy_group_id" integer NOT NULL, CONSTRAINT "PK_5ef80a70b0818cff6b0a4742fe4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7ffbfe3f441a045ccf9a8733d0" ON "mst_strategy" ("code", "mst_strategy_group_id") `);
        await queryRunner.query(`CREATE TABLE "mst_organization_group" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_5b286ebd97f61c8b365c4fc6cda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d09438ba42a19b851e993ba9cc" ON "mst_organization_group" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_organization" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "is_active" boolean NOT NULL DEFAULT true, "mst_organization_group_id" integer NOT NULL, CONSTRAINT "PK_38baee48eaae8f83309c9482fd4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_05f5244bf5cc96dc4e6906c727" ON "mst_organization" ("code", "mst_organization_group_id") `);
        await queryRunner.query(`CREATE TABLE "mst_measure" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_2a2277a7be843150feccc2a94e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_56a74ceabd8b851347f13a0412" ON "mst_measure" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_benchmark" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_c724fc896c183f19f913204cad6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_56419d86068186d9deb8ea8517" ON "mst_benchmark" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_topic" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "is_active" boolean NOT NULL DEFAULT true, "alias_code" character varying(20), CONSTRAINT "PK_434bf019eee1f8edc913edff7a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2c2bf7565525d22a76ddb53744" ON "mst_topic" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_frequency" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "interval_value" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_28b235544dd0aa75475eaff36f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3d2e45ac291cecf59344641a37" ON "mst_frequency" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_condition_operator" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "symbol" character varying(255), "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_d6610877b8943f633d122045799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d0274cd2531bc6b5c80823f3c6" ON "mst_condition_operator" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_kpi_unit" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "symbol" character varying(255), "scale_factor" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "is_percent" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6a91343c2582f198c01e6678ede" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1ca0758900495c555466c89846" ON "mst_kpi_unit" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_service_units" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "is_active" boolean NOT NULL DEFAULT true, "service_unit_group_id" integer NOT NULL, CONSTRAINT "PK_6296b45eee4a6f1b74403e8441d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_eb1f1600332005738ad1d35f25" ON "mst_service_units" ("code", "service_unit_group_id") `);
        await queryRunner.query(`CREATE TABLE "mst_service_units_group" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_9604fbc000121781258d33686ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9cd5a4f0073717442245462e8e" ON "mst_service_units_group" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_simple" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "is_active" boolean NOT NULL DEFAULT true, "simple_group_id" integer NOT NULL, CONSTRAINT "PK_5ca0e68c75dcc9c8afb6dc16925" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1989b1d33bbdaa23269f38067f" ON "mst_simple" ("code", "simple_group_id") `);
        await queryRunner.query(`CREATE TABLE "mst_simple_group" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_eaedb58c504707c937bee2d25a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6ea616bf63a17d8717508dcd08" ON "mst_simple_group" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_kpi_roles" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_16f5b60fbb3813ebf2838af49a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e8e329a991e1c82f55336e53b8" ON "mst_kpi_roles" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_system_roles" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_7f77e2f03b0d318d4a63c860063" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c45503c681370e708679e5ee3" ON "mst_system_roles" ("code") `);
        await queryRunner.query(`CREATE TABLE "mst_users" ("id" SERIAL NOT NULL, "usercode" character varying(10) NOT NULL, "description" character varying(255) NOT NULL, "usersystem_role_id" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_cc95c3c1b8f136b365791e79eab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e92b5672d0600abe3e5d751aab" ON "mst_users" ("usercode") `);
        await queryRunner.query(`CREATE TABLE "kpi_service_units_mappings" ("id" SERIAL NOT NULL, "kpi_id" integer NOT NULL, "service_unit_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_726ef484b763950e63907c4d2e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_44ce939c8e470578a3dafdd590" ON "kpi_service_units_mappings" ("kpi_id", "service_unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9faf68f028ba87daecd4b1c8d" ON "kpi_service_units_mappings" ("service_unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fbcfdda531da2969e8f687662d" ON "kpi_service_units_mappings" ("kpi_id") `);
        await queryRunner.query(`CREATE TABLE "kpi_simple_mappings" ("id" SERIAL NOT NULL, "kpi_id" integer NOT NULL, "simple_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_dfcf49b1780cfaabcae6cabdd14" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3cf3651e961028c21ff1adca29" ON "kpi_simple_mappings" ("kpi_id", "simple_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f4557eba58486e56344698252" ON "kpi_simple_mappings" ("simple_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf12527a071eb5c798d6dbb35f" ON "kpi_simple_mappings" ("kpi_id") `);
        await queryRunner.query(`CREATE TABLE "kpi_user_roles_mappings" ("id" SERIAL NOT NULL, "kpi_id" integer NOT NULL, "user_id" integer NOT NULL, "role_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_e969f1e8ec91b3f265a91af712c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b627c3d9f1ca967b953e6ebdc6" ON "kpi_user_roles_mappings" ("kpi_id", "user_id", "role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b3a1c31552ae2fda9bccad086" ON "kpi_user_roles_mappings" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4604e35c84ab2211e206bdd1e1" ON "kpi_user_roles_mappings" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3f1bb29e108c77514f437bcad" ON "kpi_user_roles_mappings" ("kpi_id") `);
        await queryRunner.query(`CREATE TABLE "kpi_strategy_mappings" ("id" SERIAL NOT NULL, "kpi_id" integer NOT NULL, "strategy_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_18469f91c34026bf258d1b594e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d38700cb80ad1dbbdc7329d44a" ON "kpi_strategy_mappings" ("kpi_id", "strategy_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_796c3b87acb24d4856de47f858" ON "kpi_strategy_mappings" ("strategy_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a0ccda59db9a2011d051303be" ON "kpi_strategy_mappings" ("kpi_id") `);
        await queryRunner.query(`CREATE TABLE "kpi_organization_mappings" ("id" SERIAL NOT NULL, "kpi_id" integer NOT NULL, "organization_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_117b7ee8cd35f745fc839c9e5c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_55156ba0cfb81325e500bff5b6" ON "kpi_organization_mappings" ("kpi_id", "organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a62a60ab7f6066e6199b115a0" ON "kpi_organization_mappings" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_13e8d6e1fba69a58dea92b127c" ON "kpi_organization_mappings" ("kpi_id") `);
        await queryRunner.query(`CREATE TABLE "kpi_definition" ("id" SERIAL NOT NULL, "topic_ref_id" integer NOT NULL, "kpi_year" integer NOT NULL, "kpi_start_date" date, "measure_ref_id" integer, "frequency_ref_id" integer NOT NULL, "unit_ref_id" integer NOT NULL, "condition_operator_ref_id" integer, "benchmark_ref_id" integer, "benchmark_target_value" double precision, "numerator" text, "denominator" text, "multiplier" double precision, "target_value" double precision, "previous_year_value" double precision, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e19d5895a1dd4418d377ad05470" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_kpi_topic_year" ON "kpi_definition" ("topic_ref_id", "kpi_year") `);
        await queryRunner.query(`CREATE TABLE "kpi_data_entry" ("id" SERIAL NOT NULL, "kpi_definition_id" integer NOT NULL, "kpi_def_year" integer NOT NULL, "kpi_def_month" integer NOT NULL, "numerator_value" double precision NOT NULL, "denominator_value" double precision, "created_by" integer, "updated_by" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('Asia/Bangkok', now()), CONSTRAINT "PK_b7358eebe4dbe469bb79512f010" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4055d290cd62afe8edb2256a4f" ON "kpi_data_entry" ("kpi_def_month") `);
        await queryRunner.query(`CREATE INDEX "IDX_76e8028667d8f192fa34db703f" ON "kpi_data_entry" ("kpi_def_year") `);
        await queryRunner.query(`CREATE INDEX "IDX_c68fe53f33bbe95deec053c878" ON "kpi_data_entry" ("kpi_definition_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_kpi_data_entry_period" ON "kpi_data_entry" ("kpi_definition_id", "kpi_def_year", "kpi_def_month") `);
        await queryRunner.query(`ALTER TABLE "mst_strategy" ADD CONSTRAINT "FK_0a7fdfe964049cac9fb8b6b2a75" FOREIGN KEY ("mst_strategy_group_id") REFERENCES "mst_strategy_group"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mst_organization" ADD CONSTRAINT "FK_6d82aac7ffa5b3c1dbdeb848031" FOREIGN KEY ("mst_organization_group_id") REFERENCES "mst_organization_group"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mst_service_units" ADD CONSTRAINT "FK_180684bcd25f67f0d1bfcfb6c09" FOREIGN KEY ("service_unit_group_id") REFERENCES "mst_service_units_group"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mst_simple" ADD CONSTRAINT "FK_66ad38680548c9bfa53761606c3" FOREIGN KEY ("simple_group_id") REFERENCES "mst_simple_group"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "kpi_service_units_mappings" ADD CONSTRAINT "FK_fbcfdda531da2969e8f687662df" FOREIGN KEY ("kpi_id") REFERENCES "kpi_definition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_service_units_mappings" ADD CONSTRAINT "FK_e9faf68f028ba87daecd4b1c8d2" FOREIGN KEY ("service_unit_id") REFERENCES "mst_service_units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_simple_mappings" ADD CONSTRAINT "FK_bf12527a071eb5c798d6dbb35f8" FOREIGN KEY ("kpi_id") REFERENCES "kpi_definition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_simple_mappings" ADD CONSTRAINT "FK_1f4557eba58486e563446982524" FOREIGN KEY ("simple_id") REFERENCES "mst_simple"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_user_roles_mappings" ADD CONSTRAINT "FK_d3f1bb29e108c77514f437bcad7" FOREIGN KEY ("kpi_id") REFERENCES "kpi_definition"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_user_roles_mappings" ADD CONSTRAINT "FK_4604e35c84ab2211e206bdd1e16" FOREIGN KEY ("user_id") REFERENCES "mst_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_user_roles_mappings" ADD CONSTRAINT "FK_1b3a1c31552ae2fda9bccad0862" FOREIGN KEY ("role_id") REFERENCES "mst_kpi_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_strategy_mappings" ADD CONSTRAINT "FK_3a0ccda59db9a2011d051303be5" FOREIGN KEY ("kpi_id") REFERENCES "kpi_definition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_strategy_mappings" ADD CONSTRAINT "FK_796c3b87acb24d4856de47f858d" FOREIGN KEY ("strategy_id") REFERENCES "mst_strategy"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_organization_mappings" ADD CONSTRAINT "FK_13e8d6e1fba69a58dea92b127ce" FOREIGN KEY ("kpi_id") REFERENCES "kpi_definition"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_organization_mappings" ADD CONSTRAINT "FK_6a62a60ab7f6066e6199b115a01" FOREIGN KEY ("organization_id") REFERENCES "mst_organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" ADD CONSTRAINT "FK_4a36ed6d8fcdd127dcec742caf0" FOREIGN KEY ("topic_ref_id") REFERENCES "mst_topic"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" ADD CONSTRAINT "FK_da497d320927e3eb02889989655" FOREIGN KEY ("measure_ref_id") REFERENCES "mst_measure"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" ADD CONSTRAINT "FK_0bd4b92bed4968cbd3059717e0b" FOREIGN KEY ("frequency_ref_id") REFERENCES "mst_frequency"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" ADD CONSTRAINT "FK_d763ed5a85cf0b4c27b3707fa86" FOREIGN KEY ("unit_ref_id") REFERENCES "mst_kpi_unit"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" ADD CONSTRAINT "FK_b3db127f2650674f2782394e0ea" FOREIGN KEY ("condition_operator_ref_id") REFERENCES "mst_condition_operator"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" ADD CONSTRAINT "FK_cb274211abaf1a5120ad757e3c6" FOREIGN KEY ("benchmark_ref_id") REFERENCES "mst_benchmark"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_data_entry" ADD CONSTRAINT "FK_c68fe53f33bbe95deec053c8787" FOREIGN KEY ("kpi_definition_id") REFERENCES "kpi_definition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_data_entry" ADD CONSTRAINT "FK_2aa89938d8c4ca9cb8c856a1083" FOREIGN KEY ("created_by") REFERENCES "mst_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_data_entry" ADD CONSTRAINT "FK_b311ae7978fa49895e3f9d55636" FOREIGN KEY ("updated_by") REFERENCES "mst_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "kpi_data_entry" DROP CONSTRAINT "FK_b311ae7978fa49895e3f9d55636"`);
        await queryRunner.query(`ALTER TABLE "kpi_data_entry" DROP CONSTRAINT "FK_2aa89938d8c4ca9cb8c856a1083"`);
        await queryRunner.query(`ALTER TABLE "kpi_data_entry" DROP CONSTRAINT "FK_c68fe53f33bbe95deec053c8787"`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" DROP CONSTRAINT "FK_cb274211abaf1a5120ad757e3c6"`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" DROP CONSTRAINT "FK_b3db127f2650674f2782394e0ea"`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" DROP CONSTRAINT "FK_d763ed5a85cf0b4c27b3707fa86"`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" DROP CONSTRAINT "FK_0bd4b92bed4968cbd3059717e0b"`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" DROP CONSTRAINT "FK_da497d320927e3eb02889989655"`);
        await queryRunner.query(`ALTER TABLE "kpi_definition" DROP CONSTRAINT "FK_4a36ed6d8fcdd127dcec742caf0"`);
        await queryRunner.query(`ALTER TABLE "kpi_organization_mappings" DROP CONSTRAINT "FK_6a62a60ab7f6066e6199b115a01"`);
        await queryRunner.query(`ALTER TABLE "kpi_organization_mappings" DROP CONSTRAINT "FK_13e8d6e1fba69a58dea92b127ce"`);
        await queryRunner.query(`ALTER TABLE "kpi_strategy_mappings" DROP CONSTRAINT "FK_796c3b87acb24d4856de47f858d"`);
        await queryRunner.query(`ALTER TABLE "kpi_strategy_mappings" DROP CONSTRAINT "FK_3a0ccda59db9a2011d051303be5"`);
        await queryRunner.query(`ALTER TABLE "kpi_user_roles_mappings" DROP CONSTRAINT "FK_1b3a1c31552ae2fda9bccad0862"`);
        await queryRunner.query(`ALTER TABLE "kpi_user_roles_mappings" DROP CONSTRAINT "FK_4604e35c84ab2211e206bdd1e16"`);
        await queryRunner.query(`ALTER TABLE "kpi_user_roles_mappings" DROP CONSTRAINT "FK_d3f1bb29e108c77514f437bcad7"`);
        await queryRunner.query(`ALTER TABLE "kpi_simple_mappings" DROP CONSTRAINT "FK_1f4557eba58486e563446982524"`);
        await queryRunner.query(`ALTER TABLE "kpi_simple_mappings" DROP CONSTRAINT "FK_bf12527a071eb5c798d6dbb35f8"`);
        await queryRunner.query(`ALTER TABLE "kpi_service_units_mappings" DROP CONSTRAINT "FK_e9faf68f028ba87daecd4b1c8d2"`);
        await queryRunner.query(`ALTER TABLE "kpi_service_units_mappings" DROP CONSTRAINT "FK_fbcfdda531da2969e8f687662df"`);
        await queryRunner.query(`ALTER TABLE "mst_simple" DROP CONSTRAINT "FK_66ad38680548c9bfa53761606c3"`);
        await queryRunner.query(`ALTER TABLE "mst_service_units" DROP CONSTRAINT "FK_180684bcd25f67f0d1bfcfb6c09"`);
        await queryRunner.query(`ALTER TABLE "mst_organization" DROP CONSTRAINT "FK_6d82aac7ffa5b3c1dbdeb848031"`);
        await queryRunner.query(`ALTER TABLE "mst_strategy" DROP CONSTRAINT "FK_0a7fdfe964049cac9fb8b6b2a75"`);
        await queryRunner.query(`DROP INDEX "public"."uq_kpi_data_entry_period"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c68fe53f33bbe95deec053c878"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76e8028667d8f192fa34db703f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4055d290cd62afe8edb2256a4f"`);
        await queryRunner.query(`DROP TABLE "kpi_data_entry"`);
        await queryRunner.query(`DROP INDEX "public"."uq_kpi_topic_year"`);
        await queryRunner.query(`DROP TABLE "kpi_definition"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13e8d6e1fba69a58dea92b127c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a62a60ab7f6066e6199b115a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55156ba0cfb81325e500bff5b6"`);
        await queryRunner.query(`DROP TABLE "kpi_organization_mappings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a0ccda59db9a2011d051303be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_796c3b87acb24d4856de47f858"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d38700cb80ad1dbbdc7329d44a"`);
        await queryRunner.query(`DROP TABLE "kpi_strategy_mappings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3f1bb29e108c77514f437bcad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4604e35c84ab2211e206bdd1e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b3a1c31552ae2fda9bccad086"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b627c3d9f1ca967b953e6ebdc6"`);
        await queryRunner.query(`DROP TABLE "kpi_user_roles_mappings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf12527a071eb5c798d6dbb35f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f4557eba58486e56344698252"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3cf3651e961028c21ff1adca29"`);
        await queryRunner.query(`DROP TABLE "kpi_simple_mappings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbcfdda531da2969e8f687662d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9faf68f028ba87daecd4b1c8d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44ce939c8e470578a3dafdd590"`);
        await queryRunner.query(`DROP TABLE "kpi_service_units_mappings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e92b5672d0600abe3e5d751aab"`);
        await queryRunner.query(`DROP TABLE "mst_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c45503c681370e708679e5ee3"`);
        await queryRunner.query(`DROP TABLE "mst_system_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8e329a991e1c82f55336e53b8"`);
        await queryRunner.query(`DROP TABLE "mst_kpi_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ea616bf63a17d8717508dcd08"`);
        await queryRunner.query(`DROP TABLE "mst_simple_group"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1989b1d33bbdaa23269f38067f"`);
        await queryRunner.query(`DROP TABLE "mst_simple"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cd5a4f0073717442245462e8e"`);
        await queryRunner.query(`DROP TABLE "mst_service_units_group"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb1f1600332005738ad1d35f25"`);
        await queryRunner.query(`DROP TABLE "mst_service_units"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ca0758900495c555466c89846"`);
        await queryRunner.query(`DROP TABLE "mst_kpi_unit"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0274cd2531bc6b5c80823f3c6"`);
        await queryRunner.query(`DROP TABLE "mst_condition_operator"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d2e45ac291cecf59344641a37"`);
        await queryRunner.query(`DROP TABLE "mst_frequency"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c2bf7565525d22a76ddb53744"`);
        await queryRunner.query(`DROP TABLE "mst_topic"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56419d86068186d9deb8ea8517"`);
        await queryRunner.query(`DROP TABLE "mst_benchmark"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56a74ceabd8b851347f13a0412"`);
        await queryRunner.query(`DROP TABLE "mst_measure"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05f5244bf5cc96dc4e6906c727"`);
        await queryRunner.query(`DROP TABLE "mst_organization"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d09438ba42a19b851e993ba9cc"`);
        await queryRunner.query(`DROP TABLE "mst_organization_group"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ffbfe3f441a045ccf9a8733d0"`);
        await queryRunner.query(`DROP TABLE "mst_strategy"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c90519c0ca5335fb813b713d75"`);
        await queryRunner.query(`DROP TABLE "mst_strategy_group"`);
    }

}
